{"__error": {"error_code": "shareclasses-12345", "status": 404, "user_message": "Nothing Found against provided ID.", "user_error_code": "12345", "correlation_id": "e9f5a26f-ed69-4ecf-b03b-59d8c9b0fa0b", "message": "0 records Found. Please check your URL", "more_info": "", "additional_info": ["Traceback(most recent call last):\n", "  File `/var/task/lambdas/data_access_service_system_api/system_api_manager_shareclass.py`, line 104, in lambda_handler\n    user_message=ApplicationErrors.EDL_ERROR_MESSAGE_USER_NO_RECORDS_FOUND)\n", "Error Type -> NoRecordsFoundException"]}}