{"__error": {"error_code": "shareclasses-12345", "status": 404, "user_message": "Exception occurred while processing Shareclasses resource", "user_error_code": "12345", "correlation_id": "bdb7af3b-3454-4774-91af-e0718acfa35d", "message": "float() argument must be a string or a number, not `NoneType`", "more_info": "", "additional_info": ["Traceback(most recent call last):\n", "  File `/var/task/lambdas/data_access_service_system_api/system_api_manager_shareclass.py`, line 80, in lambda_handler\n    response = ShareclassPerformance.get_result(self=None, sys_log=log)\n", "  File `/var/task/lambdas/data_access_service_system_api/shareclass_performance.py`, line 55, in get_result\n    response = ShareclassPerformance.get_g10k_result(self,growthscheme, sys_log)\n", "  File `/var/task/lambdas/data_access_service_system_api/shareclass_performance.py`, line 230, in get_g10k_result\n    fundreturngross1m = float(dic[`fundreturngross1m`])\n", "Error Type -> GeneralException"]}}